/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Dell
 */
public class Detalles extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    /**
     * Creates new form Principal
     */
    public Detalles() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Tittle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Tree3 = new javax.swing.JTextField();
        jTextField_Tree4 = new javax.swing.JTextField();
        jTextField_Tree5 = new javax.swing.JTextField();
        jTextField_Tree6 = new javax.swing.JTextField();
        jTextField_Tree7 = new javax.swing.JTextField();
        jTextField_Tree8 = new javax.swing.JTextField();
        jTextField_Tree9 = new javax.swing.JTextField();
        jTextField_Tree10 = new javax.swing.JTextField();
        jTextField_Tree11 = new javax.swing.JTextField();
        jTextField_Tree13 = new javax.swing.JTextField();
        jTextField_Tree2 = new javax.swing.JTextField();
        jTextField_Chain = new javax.swing.JTextField();
        jTextField_Tree = new javax.swing.JTextField();
        jButton_Confirmar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton_Ejecutar = new javax.swing.JButton();
        jButton_Mostrar = new javax.swing.JButton();
        jLabel_drag = new javax.swing.JLabel();
        jLabel_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.95F);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Tittle.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel_Tittle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Tittle.setText("Detalles");
        getContentPane().add(jLabel_Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 280, 30));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, 20));

        jTextField_Tree3.setEditable(false);
        jTextField_Tree3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Tree3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 40, 20));

        jTextField_Tree4.setEditable(false);
        jTextField_Tree4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Tree4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 40, 20));

        jTextField_Tree5.setEditable(false);
        jTextField_Tree5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Tree5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 40, 20));

        jTextField_Tree6.setEditable(false);
        jTextField_Tree6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Tree6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 40, 20));

        jTextField_Tree7.setEditable(false);
        jTextField_Tree7.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Tree7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 40, 20));

        jTextField_Tree8.setEditable(false);
        jTextField_Tree8.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Tree8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 40, 20));

        jTextField_Tree9.setEditable(false);
        jTextField_Tree9.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Tree9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 40, 20));

        jTextField_Tree10.setEditable(false);
        jTextField_Tree10.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Tree10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 40, 20));

        jTextField_Tree11.setEditable(false);
        jTextField_Tree11.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Tree11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 40, 20));

        jTextField_Tree13.setEditable(false);
        jTextField_Tree13.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Tree13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 40, 20));

        jTextField_Tree2.setEditable(false);
        jTextField_Tree2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Tree2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 40, 20));

        jTextField_Chain.setEditable(false);
        jTextField_Chain.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Chain.setOpaque(false);
        jTextField_Chain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ChainActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Chain, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 340, 30));

        jTextField_Tree.setEditable(false);
        jTextField_Tree.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTextField_Tree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TreeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tree, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 200, 170));

        jButton_Confirmar.setText("Confirmar Cambios");
        getContentPane().add(jButton_Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 190, 30));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("x");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 30));

        jButton_Ejecutar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Ejecutar.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jButton_Ejecutar.setText("Guardar");
        getContentPane().add(jButton_Ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 90, 30));

        jButton_Mostrar.setBackground(new java.awt.Color(204, 0, 0));
        jButton_Mostrar.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jButton_Mostrar.setText("Salir");
        jButton_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 100, 30));

        jLabel_drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_dragMouseDragged(evt);
            }
        });
        jLabel_drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_dragMousePressed(evt);
            }
        });
        getContentPane().add(jLabel_drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 320));

        jLabel_background.setBackground(new java.awt.Color(0, 51, 153));
        jLabel_background.setText("                              ");
        jLabel_background.setToolTipText("");
        jLabel_background.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.gray));
        jLabel_background.setOpaque(true);
        getContentPane().add(jLabel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_TreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TreeActionPerformed

    private void jLabel_dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dragMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel_dragMouseDragged

    private void jLabel_dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dragMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel_dragMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_ChainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ChainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ChainActionPerformed

    private void jButton_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MostrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_MostrarActionPerformed

    private void jTextField_Tree2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Tree2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Tree2ActionPerformed

    private void jTextField_Tree3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Tree3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Tree3ActionPerformed

    private void jTextField_Tree4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Tree4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Tree4ActionPerformed

    private void jTextField_Tree5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Tree5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Tree5ActionPerformed

    private void jTextField_Tree6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Tree6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Tree6ActionPerformed

    private void jTextField_Tree7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Tree7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Tree7ActionPerformed

    private void jTextField_Tree8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Tree8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Tree8ActionPerformed

    private void jTextField_Tree9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Tree9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Tree9ActionPerformed

    private void jTextField_Tree10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Tree10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Tree10ActionPerformed

    private void jTextField_Tree11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Tree11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Tree11ActionPerformed

    private void jTextField_Tree13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Tree13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Tree13ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detalles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Confirmar;
    private javax.swing.JButton jButton_Ejecutar;
    private javax.swing.JButton jButton_Mostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Tittle;
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JLabel jLabel_drag;
    private javax.swing.JTextField jTextField_Chain;
    private javax.swing.JTextField jTextField_Tree;
    private javax.swing.JTextField jTextField_Tree10;
    private javax.swing.JTextField jTextField_Tree11;
    private javax.swing.JTextField jTextField_Tree13;
    private javax.swing.JTextField jTextField_Tree2;
    private javax.swing.JTextField jTextField_Tree3;
    private javax.swing.JTextField jTextField_Tree4;
    private javax.swing.JTextField jTextField_Tree5;
    private javax.swing.JTextField jTextField_Tree6;
    private javax.swing.JTextField jTextField_Tree7;
    private javax.swing.JTextField jTextField_Tree8;
    private javax.swing.JTextField jTextField_Tree9;
    // End of variables declaration//GEN-END:variables
}
