/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import algorithm.GrammarRNA;
import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Dell
 */
public class MainGUI extends javax.swing.JFrame {

    Detalles details;
    int xMouse;
    int yMouse;
    GrammarRNA grammarRNA = new GrammarRNA();

    /**
     * Creates new form Principal
     */
    public MainGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        details = new Detalles(grammarRNA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Tittle = new javax.swing.JLabel();
        jScrollPane_Tree = new javax.swing.JScrollPane();
        jTextArea_Tree = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton_Ejecutar = new javax.swing.JButton();
        jButton_Mostrar = new javax.swing.JButton();
        jButton_Detalles = new javax.swing.JButton();
        jLabel_Iteracion = new javax.swing.JLabel();
        jlabel_Tamano = new javax.swing.JLabel();
        jLabel_Tiempo = new javax.swing.JLabel();
        jTextField_IteracionNumber = new javax.swing.JTextField();
        jTextField_TamanoNumber = new javax.swing.JTextField();
        jTextField_TiempoNumber = new javax.swing.JTextField();
        jSlider_Iteracion = new javax.swing.JSlider();
        jSlider_Tamano = new javax.swing.JSlider();
        jSlider_Tiempo = new javax.swing.JSlider();
        jLabel_drag = new javax.swing.JLabel();
        jLabel_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.95F);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Tittle.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_Tittle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Tittle.setText("PCFG: Predicción RNA");
        getContentPane().add(jLabel_Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 280, 30));

        jTextArea_Tree.setEditable(false);
        jTextArea_Tree.setColumns(20);
        jTextArea_Tree.setRows(5);
        jScrollPane_Tree.setViewportView(jTextArea_Tree);

        getContentPane().add(jScrollPane_Tree, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 280, 200));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("_");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 40, 30));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("x");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 40, 30));

        jButton_Ejecutar.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Ejecutar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton_Ejecutar.setText("Ejecutar");
        jButton_Ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EjecutarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 100, 70));

        jButton_Mostrar.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Mostrar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton_Mostrar.setText("Mostrar");
        jButton_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 143, 100, 60));

        jButton_Detalles.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Detalles.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton_Detalles.setText("Ver detalles");
        jButton_Detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DetallesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 207, 100, 30));

        jLabel_Iteracion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel_Iteracion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Iteracion.setText("Iteración");
        getContentPane().add(jLabel_Iteracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 20));

        jlabel_Tamano.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlabel_Tamano.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Tamano.setText("Tamaño");
        getContentPane().add(jlabel_Tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 20));

        jLabel_Tiempo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel_Tiempo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Tiempo.setText("Tiempo");
        getContentPane().add(jLabel_Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, 20));

        jTextField_IteracionNumber.setBackground(new java.awt.Color(0, 51, 153));
        jTextField_IteracionNumber.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField_IteracionNumber.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_IteracionNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_IteracionNumber.setText("101");
        jTextField_IteracionNumber.setBorder(null);
        jTextField_IteracionNumber.setOpaque(false);
        jTextField_IteracionNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IteracionNumberActionPerformed(evt);
            }
        });
        jTextField_IteracionNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_IteracionNumberKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_IteracionNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 30, 30));

        jTextField_TamanoNumber.setEditable(false);
        jTextField_TamanoNumber.setBackground(new java.awt.Color(0, 51, 153));
        jTextField_TamanoNumber.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField_TamanoNumber.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_TamanoNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_TamanoNumber.setText("10");
        jTextField_TamanoNumber.setBorder(null);
        jTextField_TamanoNumber.setOpaque(false);
        jTextField_TamanoNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_TamanoNumberKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_TamanoNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 30, 30));

        jTextField_TiempoNumber.setEditable(false);
        jTextField_TiempoNumber.setBackground(new java.awt.Color(0, 51, 153));
        jTextField_TiempoNumber.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField_TiempoNumber.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_TiempoNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_TiempoNumber.setText("1");
        jTextField_TiempoNumber.setBorder(null);
        jTextField_TiempoNumber.setOpaque(false);
        jTextField_TiempoNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TiempoNumberActionPerformed(evt);
            }
        });
        jTextField_TiempoNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_TiempoNumberKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_TiempoNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 30, 30));

        jSlider_Iteracion.setBackground(new java.awt.Color(0, 0, 0));
        jSlider_Iteracion.setForeground(new java.awt.Color(255, 255, 255));
        jSlider_Iteracion.setMaximum(1001);
        jSlider_Iteracion.setMinimum(1);
        jSlider_Iteracion.setMinorTickSpacing(100);
        jSlider_Iteracion.setPaintLabels(true);
        jSlider_Iteracion.setSnapToTicks(true);
        jSlider_Iteracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider_Iteracion.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSlider_Iteracion.setOpaque(false);
        jSlider_Iteracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider_IteracionMouseReleased(evt);
            }
        });
        getContentPane().add(jSlider_Iteracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 510, 20));

        jSlider_Tamano.setBackground(new java.awt.Color(0, 0, 0));
        jSlider_Tamano.setForeground(new java.awt.Color(255, 255, 255));
        jSlider_Tamano.setMaximum(18);
        jSlider_Tamano.setMinimum(6);
        jSlider_Tamano.setMinorTickSpacing(2);
        jSlider_Tamano.setPaintLabels(true);
        jSlider_Tamano.setSnapToTicks(true);
        jSlider_Tamano.setValue(10);
        jSlider_Tamano.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider_Tamano.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSlider_Tamano.setOpaque(false);
        jSlider_Tamano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider_TamanoMouseReleased(evt);
            }
        });
        getContentPane().add(jSlider_Tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 510, 20));

        jSlider_Tiempo.setBackground(new java.awt.Color(0, 0, 0));
        jSlider_Tiempo.setForeground(new java.awt.Color(255, 255, 255));
        jSlider_Tiempo.setMaximum(7);
        jSlider_Tiempo.setMinimum(1);
        jSlider_Tiempo.setMinorTickSpacing(1);
        jSlider_Tiempo.setPaintLabels(true);
        jSlider_Tiempo.setSnapToTicks(true);
        jSlider_Tiempo.setValue(1);
        jSlider_Tiempo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider_Tiempo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSlider_Tiempo.setOpaque(false);
        jSlider_Tiempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider_TiempoMouseReleased(evt);
            }
        });
        getContentPane().add(jSlider_Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 510, 20));

        jLabel_drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_dragMouseDragged(evt);
            }
        });
        jLabel_drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_dragMousePressed(evt);
            }
        });
        getContentPane().add(jLabel_drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 440));

        jLabel_background.setBackground(new java.awt.Color(0, 51, 153));
        jLabel_background.setText("                              ");
        jLabel_background.setToolTipText("");
        jLabel_background.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.gray));
        jLabel_background.setOpaque(true);
        getContentPane().add(jLabel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_DetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DetallesActionPerformed
        // TODO add your handling code here:
        details = new Detalles(grammarRNA);
        details.setVisible(true);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
    }//GEN-LAST:event_jButton_DetallesActionPerformed

    public void updateProbability(double[] probability){
        grammarRNA.setProbability(probability);
    }
    
    private void jLabel_dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dragMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel_dragMouseDragged

    private void jLabel_dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dragMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel_dragMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_IteracionNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IteracionNumberActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_IteracionNumberActionPerformed

    private void jTextField_TiempoNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TiempoNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TiempoNumberActionPerformed

    private void jTextField_TiempoNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TiempoNumberKeyPressed
        // TODO add your handling code here:
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                jSlider_Tiempo.setValue(Integer.parseInt(jTextField_TiempoNumber.getText()));
            }
        } catch (Exception e) {
            jTextField_TiempoNumber.setText("10");
            jSlider_Tiempo.setValue(Integer.parseInt(jTextField_TiempoNumber.getText()));
        }
        
    }//GEN-LAST:event_jTextField_TiempoNumberKeyPressed

    private void jSlider_TiempoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider_TiempoMouseReleased
        // TODO add your handling code here:
        jTextField_TiempoNumber.setText(String.valueOf(jSlider_Tiempo.getValue()));
    }//GEN-LAST:event_jSlider_TiempoMouseReleased

    private void jTextField_TamanoNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TamanoNumberKeyPressed
        // TODO add your handling code here:
        try {
            
            if(Integer.parseInt(jTextField_TamanoNumber.getText())%2 != 0){
                jTextField_TamanoNumber.setText(String.valueOf(Integer.parseInt(jTextField_TamanoNumber.getText()) + 1));
            }
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                jSlider_Tamano.setValue(Integer.parseInt(jTextField_TamanoNumber.getText()));
            }
        } catch (Exception e) {
            jTextField_TamanoNumber.setText("10");
            jSlider_Tamano.setValue(Integer.parseInt(jTextField_TamanoNumber.getText()));
        }
    }//GEN-LAST:event_jTextField_TamanoNumberKeyPressed

    private void jSlider_TamanoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider_TamanoMouseReleased
        // TODO add your handling code here:
        jTextField_TamanoNumber.setText(String.valueOf(jSlider_Tamano.getValue()));
        
        jSlider_Tiempo.setMinorTickSpacing(1);
        jSlider_Tiempo.setMaximum(((jSlider_Tamano.getValue() - 4)/2));
        jSlider_Tiempo.setValue(1);
        jTextField_TiempoNumber.setText(String.valueOf(jSlider_Tiempo.getValue()));
    }//GEN-LAST:event_jSlider_TamanoMouseReleased

    private void jTextField_IteracionNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IteracionNumberKeyPressed
        // TODO add your handling code here:
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if(Integer.parseInt(jTextField_IteracionNumber.getText()) > 1001){
                    jSlider_Iteracion.setValue(1001);
                    jTextField_IteracionNumber.setText("1001");
                }
                else if(Integer.parseInt(jTextField_IteracionNumber.getText()) < 1){
                    jSlider_Iteracion.setValue(1);
                    jTextField_IteracionNumber.setText("1");
                }
                else{
                    jSlider_Iteracion.setValue(Integer.parseInt(jTextField_IteracionNumber.getText()));
                }
            }
        } catch (Exception e) {
            jTextField_IteracionNumber.setText("10");
            jSlider_Iteracion.setValue(Integer.parseInt(jTextField_IteracionNumber.getText()));
        }
    }//GEN-LAST:event_jTextField_IteracionNumberKeyPressed

    private void jSlider_IteracionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider_IteracionMouseReleased
        // TODO add your handling code here:
        jTextField_IteracionNumber.setText(String.valueOf(jSlider_Iteracion.getValue()));        
    }//GEN-LAST:event_jSlider_IteracionMouseReleased

    private void jButton_EjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EjecutarActionPerformed
         // TODO add your handling code here:
         grammarRNA.setProbability(details.grammarRNA.getProbability());
         grammarRNA.run(jSlider_Tamano.getValue(), jSlider_Iteracion.getValue());
         jTextArea_Tree.setText(grammarRNA.showResult(jSlider_Tiempo.getValue() -1 ).toString() );
    }//GEN-LAST:event_jButton_EjecutarActionPerformed

    private void jButton_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MostrarActionPerformed
        // TODO add your handling code here:
         jTextArea_Tree.setText(grammarRNA.showResult(jSlider_Tiempo.getValue() -1 ).toString());
    }//GEN-LAST:event_jButton_MostrarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Detalles;
    private javax.swing.JButton jButton_Ejecutar;
    private javax.swing.JButton jButton_Mostrar;
    private javax.swing.JLabel jLabel_Iteracion;
    private javax.swing.JLabel jLabel_Tiempo;
    private javax.swing.JLabel jLabel_Tittle;
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JLabel jLabel_drag;
    private javax.swing.JScrollPane jScrollPane_Tree;
    private javax.swing.JSlider jSlider_Iteracion;
    private javax.swing.JSlider jSlider_Tamano;
    private javax.swing.JSlider jSlider_Tiempo;
    private javax.swing.JTextArea jTextArea_Tree;
    private javax.swing.JTextField jTextField_IteracionNumber;
    private javax.swing.JTextField jTextField_TamanoNumber;
    private javax.swing.JTextField jTextField_TiempoNumber;
    private javax.swing.JLabel jlabel_Tamano;
    // End of variables declaration//GEN-END:variables
}
